const sources = { transactions: 'Augmented_IndiaTransactMultiFacet2024.csv', music: 'spotify_history.csv', household: 'Daily Household Transactions.csv' };
const state = { receipts: [], filter: 'all', query: '', sort: 'new', selected: null, insightIndex: 0 };

const $ = (selector) => document.querySelector(selector);
const formatDate = (date) => date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
const parseCsv = (text) => { const rows = []; let row = [], cell = '', quote = false; for (let i = 0; i < text.length; i += 1) { const char = text[i], next = text[i + 1]; if (char === '"' && quote && next === '"') { cell += '"'; i += 1; } else if (char === '"') quote = !quote; else if (char === ',' && !quote) { row.push(cell); cell = ''; } else if ((char === '\n' || char === '\r') && !quote) { if (char === '\r' && next === '\n') i += 1; row.push(cell); if (row.some(Boolean)) rows.push(row); row = []; cell = ''; } else cell += char; } if (cell || row.length) { row.push(cell); rows.push(row); } const headers = rows.shift().map((header) => header.trim()); return rows.map((values) => Object.fromEntries(headers.map((header, index) => [header, (values[index] || '').trim()]))); };
const safeDate = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; };
const clean = (value, fallback) => value && value !== 'null' ? value : fallback;

async function loadArchive() {
  const [transactionsText, musicText, householdText] = await Promise.all(Object.values(sources).map((source) => fetch(source).then((response) => response.text())));
  const transactions = parseCsv(transactionsText).filter((item) => safeDate(item.trans_date_trans_time)).map((item) => ({ type: 'money', date: safeDate(item.trans_date_trans_time), name: clean(item.merchant, `${clean(item.category, 'Everyday')} receipt`), sub: `${clean(item.category, 'uncategorised')} · ${clean(item.city, clean(item.state, 'somewhere'))}`, amount: item.amt ? `₹${Number(item.amt).toLocaleString('en-IN', { maximumFractionDigits: 0 })}` : '', category: clean(item.category, 'other'), icon: '₹', place: clean(item.city, clean(item.state, '')) }));
  const music = parseCsv(musicText).filter((item) => safeDate(item.ts)).map((item) => ({ type: 'music', date: safeDate(item.ts), name: clean(item.track_name, 'Untitled track'), sub: `${clean(item.artist_name, 'Unknown artist')} · ${Math.round(Number(item.ms_played || 0) / 60000)} min listen`, amount: '', category: 'music', icon: '♫', place: '', night: safeDate(item.ts).getHours() >= 20 || safeDate(item.ts).getHours() < 5 }));
  const household = parseCsv(householdText).filter((item) => safeDate(item.Date)).map((item) => ({ type: 'money', date: safeDate(item.Date), name: clean(item.Note, clean(item.Subcategory, clean(item.Category, 'Household receipt'))), sub: `${clean(item.Category, 'daily life')} · ${clean(item.Mode, 'cash')}`, amount: item.Amount ? `₹${Number(item.Amount).toLocaleString('en-IN', { maximumFractionDigits: 0 })}` : '', category: clean(item.Category, 'other'), icon: '₹', place: '' }));
  state.receipts = [...transactions.slice(0, 420), ...music.slice(0, 420), ...household.slice(0, 240)].map((receipt, index) => ({ ...receipt, id: index, night: receipt.night || receipt.date.getHours() >= 20 || receipt.date.getHours() < 5 })).sort((a, b) => b.date - a.date);
  render();
}

function getFiltered() { return state.receipts.filter((receipt) => { const haystack = `${receipt.name} ${receipt.sub} ${receipt.category} ${receipt.place}`.toLowerCase(); const typeMatch = state.filter === 'all' || state.filter === 'music' && receipt.type === 'music' || state.filter === 'money' && receipt.type === 'money' || state.filter === 'places' && receipt.place; return typeMatch && haystack.includes(state.query.toLowerCase()); }).sort((a, b) => state.sort === 'new' ? b.date - a.date : a.date - b.date); }
function categoryLabel(category) { return category.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function renderReceipts() { const filtered = getFiltered().slice(0, 75); $('#receiptList').innerHTML = filtered.map((receipt) => `<article class="receipt ${state.selected === receipt.id ? 'selected' : ''}" data-id="${receipt.id}" data-type="${receipt.type}" tabindex="0" role="button" aria-label="Open receipt: ${receipt.name}"><span class="receipt-date">${formatDate(receipt.date)}<br>${receipt.date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><span class="receipt-icon" aria-hidden="true">${receipt.icon}</span><div><div class="receipt-name">${receipt.name}</div><div class="receipt-sub">${receipt.sub}</div></div><span class="receipt-amount">${receipt.amount}</span></article>`).join(''); $('#emptyState').style.display = filtered.length ? 'none' : 'block'; document.querySelectorAll('.receipt').forEach((element) => { const open = () => selectReceipt(Number(element.dataset.id)); element.addEventListener('click', open); element.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open(); } }); }); }
function selectReceipt(id) { state.selected = id; const receipt = state.receipts.find((item) => item.id === id); if (!receipt) return; $('#threadTitle').innerHTML = `${receipt.name.slice(0, 22)}<br><em>left a trace.</em>`; $('#threadCopy').textContent = `${formatDate(receipt.date)} at ${receipt.date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · ${receipt.sub}. One small moment, now connected to the rest.`; $('#threadMeta').textContent = `${categoryLabel(receipt.category)} / ${receipt.type}`; renderReceipts(); document.querySelector('.thread-panel').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function renderInsights() { const receipts = state.receipts; const categoryCounts = receipts.reduce((counts, item) => { counts[item.category] = (counts[item.category] || 0) + 1; return counts; }, {}); const [topCategory, topCount] = Object.entries(categoryCounts).sort((a, b) => b[1] - a[1])[0] || ['—', 0]; const places = receipts.reduce((counts, item) => { if (item.place) counts[item.place] = (counts[item.place] || 0) + 1; return counts; }, {}); const topPlace = Object.entries(places).sort((a, b) => b[1] - a[1])[0]?.[0] || 'Unknown'; $('#heroCount').textContent = receipts.length > 999 ? `${Math.round(receipts.length / 100) / 10}k` : receipts.length; $('#allCount').textContent = receipts.length; $('#topCategory').textContent = categoryLabel(topCategory); $('#topCategoryCount').textContent = `${topCount.toLocaleString()} traces in the archive`; $('#nightCount').textContent = receipts.filter((item) => item.night).length.toLocaleString(); $('#topPlace').textContent = topPlace; $('#dataStatus').textContent = `${receipts.length.toLocaleString()} traces connected`; }
function renderChapters() { const music = state.receipts.filter((item) => item.type === 'music'); const money = state.receipts.filter((item) => item.type === 'money'); const night = state.receipts.filter((item) => item.night); const chapters = [{ number: '01', title: 'The after-hours self', copy: `There are ${night.length.toLocaleString()} traces after 8 PM. The day has a different texture when it is no longer performing.`, meta: 'night / ritual / repeat' }, { number: '02', title: 'What you returned to', copy: `${categoryLabel(music[0]?.category || 'music')} keeps the archive moving. The songs are not background; they are timestamps with a pulse.`, meta: `${music.length.toLocaleString()} listening moments` }, { number: '03', title: 'A life in small choices', copy: `${money.length.toLocaleString()} practical traces sit beside the more memorable ones. Meaning lives in both.`, meta: 'spend / habit / care' }]; $('#chapterGrid').innerHTML = chapters.map((chapter) => `<article class="chapter"><span class="chapter-number">${chapter.number}</span><h3>${chapter.title}</h3><p>${chapter.copy}</p><span>${chapter.meta}</span></article>`).join(''); }
function render() { renderInsights(); renderReceipts(); renderChapters(); }
$('#searchInput').addEventListener('input', (event) => { state.query = event.target.value; renderReceipts(); });
$('#sortSelect').addEventListener('change', (event) => { state.sort = event.target.value; renderReceipts(); });
$('#filterGroup').addEventListener('click', (event) => { const button = event.target.closest('.filter'); if (!button) return; state.filter = button.dataset.filter; document.querySelectorAll('.filter').forEach((item) => item.classList.toggle('active', item === button)); renderReceipts(); });
$('#surpriseButton').addEventListener('click', () => { const night = state.receipts.filter((item) => item.night); if (night.length) { selectReceipt(night[Math.floor(Math.random() * night.length)].id); $('#storyTitle').textContent = 'You kept your own hours.'; $('#storyCopy').textContent = `${night.length.toLocaleString()} moments happened after dark. That is not noise. That is a rhythm.`; } });
$('#storyButton').addEventListener('click', () => $('#surpriseButton').click());
$('#threadButton').addEventListener('click', () => { const current = state.receipts.find((item) => item.id === state.selected); const related = current ? state.receipts.filter((item) => item.type === current.type && item.id !== current.id) : state.receipts; if (related.length) selectReceipt(related[Math.floor(Math.random() * related.length)].id); });
$('#closeThread').addEventListener('click', () => { state.selected = null; $('#threadTitle').innerHTML = 'The late-night<br><em>blue hour.</em>'; $('#threadCopy').textContent = 'Some patterns only show up when the day has gone quiet.'; renderReceipts(); });
loadArchive().catch((error) => { $('#dataStatus').textContent = 'archive needs a local server'; $('#receiptList').innerHTML = '<div class="empty-state" style="display:block">Open this folder through a local server to let the archive read its source files.</div>'; console.error(error); });