import { loadArchive } from './src/data/archive.js';
import { categoryLabel, filterReceipts } from './src/domain/receipts.js';

const state = { receipts: [], filter: 'all', query: '', sort: 'new', selected: null };

const $ = (selector) => document.querySelector(selector);
const formatDate = (date) => date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

function getFiltered() { return filterReceipts(state.receipts, state); }
function renderReceipts() { const filtered = getFiltered().slice(0, 75); $('#receiptList').innerHTML = filtered.map((receipt) => `<article class="receipt ${state.selected === receipt.id ? 'selected' : ''}" data-id="${receipt.id}" data-type="${receipt.type}" tabindex="0" role="button" aria-label="Open receipt: ${receipt.name}"><span class="receipt-date">${formatDate(receipt.date)}<br>${receipt.date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><span class="receipt-icon" aria-hidden="true">${receipt.icon}</span><div><div class="receipt-name">${receipt.name}</div><div class="receipt-sub">${receipt.sub}</div></div><span class="receipt-amount">${receipt.amount}</span></article>`).join(''); $('#emptyState').style.display = filtered.length ? 'none' : 'block'; document.querySelectorAll('.receipt').forEach((element) => { const open = () => selectReceipt(Number(element.dataset.id)); element.addEventListener('click', open); element.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open(); } }); }); }
function selectReceipt(id) { state.selected = id; const receipt = state.receipts.find((item) => item.id === id); if (!receipt) return; $('#threadTitle').innerHTML = `${receipt.name.slice(0, 22)}<br><em>left a trace.</em>`; $('#threadCopy').textContent = `${formatDate(receipt.date)} at ${receipt.date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · ${receipt.sub}. One small moment, now connected to the rest.`; $('#threadMeta').textContent = `${categoryLabel(receipt.category)} / ${receipt.type}`; renderReceipts(); document.querySelector('.thread-panel').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function renderInsights() { const receipts = state.receipts; const categoryCounts = receipts.reduce((counts, item) => { counts[item.category] = (counts[item.category] || 0) + 1; return counts; }, {}); const [topCategory, topCount] = Object.entries(categoryCounts).sort((a, b) => b[1] - a[1])[0] || ['—', 0]; const places = receipts.reduce((counts, item) => { if (item.place) counts[item.place] = (counts[item.place] || 0) + 1; return counts; }, {}); const topPlace = Object.entries(places).sort((a, b) => b[1] - a[1])[0]?.[0] || 'Unknown'; $('#heroCount').textContent = receipts.length > 999 ? `${Math.round(receipts.length / 100) / 10}k` : receipts.length; $('#allCount').textContent = receipts.length; $('#topCategory').textContent = categoryLabel(topCategory); $('#topCategoryCount').textContent = `${topCount.toLocaleString()} traces in the archive`; $('#nightCount').textContent = receipts.filter((item) => item.night).length.toLocaleString(); $('#topPlace').textContent = topPlace; $('#dataStatus').textContent = `${receipts.length.toLocaleString()} traces connected`; }
function renderConnections() { const receipts = state.receipts; const groups = [{ key: 'music', label: 'Music', icon: '♫', color: 'yellow', count: receipts.filter((item) => item.type === 'music').length }, { key: 'money', label: 'Money', icon: '₹', color: 'coral', count: receipts.filter((item) => item.type === 'money').length }, { key: 'places', label: 'Places', icon: '⌖', color: 'teal', count: receipts.filter((item) => item.place).length }, { key: 'night', label: 'After dark', icon: '☾', color: 'blue', count: receipts.filter((item) => item.night).length }]; const links = 6; $('#connectionCount').textContent = links; $('#connectionMap').innerHTML = `<div class="map-lines" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div>${groups.map((group, index) => `<button class="map-node node-${index + 1} ${group.color}" data-map-filter="${group.key}" aria-label="Explore ${group.label}, ${group.count} receipts"><span>${group.icon}</span><strong>${group.label}</strong><small>${group.count.toLocaleString()} traces</small></button>`).join('')}<div class="map-core"><strong>${receipts.length.toLocaleString()}</strong><span>small<br>moments</span></div>`; document.querySelectorAll('.map-node').forEach((node) => node.addEventListener('click', () => { const filter = node.dataset.mapFilter; state.filter = filter === 'night' ? 'all' : filter; document.querySelectorAll('.filter').forEach((item) => item.classList.toggle('active', item.dataset.filter === state.filter)); $('#searchInput').value = ''; state.query = ''; $('#connectionTitle').textContent = `${node.querySelector('strong').textContent} keeps returning.`; $('#connectionCopy').textContent = `Follow ${node.querySelector('strong').textContent.toLowerCase()} through the archive. The repetition is part of the story.`; renderReceipts(); $('#explore').scrollIntoView({ behavior: 'smooth' }); })); }
function renderChapters() { const music = state.receipts.filter((item) => item.type === 'music'); const money = state.receipts.filter((item) => item.type === 'money'); const night = state.receipts.filter((item) => item.night); const chapters = [{ number: '01', title: 'The after-hours self', copy: `There are ${night.length.toLocaleString()} traces after 8 PM. The day has a different texture when it is no longer performing.`, meta: 'night / ritual / repeat' }, { number: '02', title: 'What you returned to', copy: `${categoryLabel(music[0]?.category || 'music')} keeps the archive moving. The songs are not background; they are timestamps with a pulse.`, meta: `${music.length.toLocaleString()} listening moments` }, { number: '03', title: 'A life in small choices', copy: `${money.length.toLocaleString()} practical traces sit beside the more memorable ones. Meaning lives in both.`, meta: 'spend / habit / care' }]; $('#chapterGrid').innerHTML = chapters.map((chapter) => `<article class="chapter"><span class="chapter-number">${chapter.number}</span><h3>${chapter.title}</h3><p>${chapter.copy}</p><span>${chapter.meta}</span></article>`).join(''); }
function render() { renderInsights(); renderConnections(); renderReceipts(); renderChapters(); }
$('#searchInput').addEventListener('input', (event) => { state.query = event.target.value; renderReceipts(); });
$('#sortSelect').addEventListener('change', (event) => { state.sort = event.target.value; renderReceipts(); });
$('#filterGroup').addEventListener('click', (event) => { const button = event.target.closest('.filter'); if (!button) return; state.filter = button.dataset.filter; document.querySelectorAll('.filter').forEach((item) => item.classList.toggle('active', item === button)); renderReceipts(); });
$('#surpriseButton').addEventListener('click', () => { const night = state.receipts.filter((item) => item.night); if (night.length) { selectReceipt(night[Math.floor(Math.random() * night.length)].id); $('#storyTitle').textContent = 'You kept your own hours.'; $('#storyCopy').textContent = `${night.length.toLocaleString()} moments happened after dark. That is not noise. That is a rhythm.`; } });
$('#storyButton').addEventListener('click', () => $('#surpriseButton').click());
$('#connectionAction').addEventListener('click', () => $('#explore').scrollIntoView({ behavior: 'smooth' }));
$('#threadButton').addEventListener('click', () => { const current = state.receipts.find((item) => item.id === state.selected); const related = current ? state.receipts.filter((item) => item.type === current.type && item.id !== current.id) : state.receipts; if (related.length) selectReceipt(related[Math.floor(Math.random() * related.length)].id); });
$('#closeThread').addEventListener('click', () => { state.selected = null; $('#threadTitle').innerHTML = 'The late-night<br><em>blue hour.</em>'; $('#threadCopy').textContent = 'Some patterns only show up when the day has gone quiet.'; renderReceipts(); });
loadArchive().then((receipts) => { state.receipts = receipts; render(); }).catch((error) => { $('#dataStatus').textContent = 'archive needs a local server'; $('#receiptList').innerHTML = '<div class="empty-state" style="display:block">Open this folder through a local server to let the archive read its source files.</div>'; console.error(error); });